/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppManagerRouteImport } from './routes/_app/manager'
import { Route as AppManagerIndexRouteImport } from './routes/_app/manager/index'
import { Route as AppManagerMoneyRouteImport } from './routes/_app/manager/money'
import { Route as AppManagerPantryRouteImport } from './routes/_app/manager/pantry'
import { Route as AppManagerPassRouteImport } from './routes/_app/manager/pass'
import { Route as AppManagerPeopleRouteImport } from './routes/_app/manager/people'
import { Route as AppManagerScheduleRouteImport } from './routes/_app/manager/schedule'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagerRoute = AppManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerIndexRoute = AppManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerMoneyRoute = AppManagerMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerPantryRoute = AppManagerPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerPassRoute = AppManagerPassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerPeopleRoute = AppManagerPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppManagerRoute,
} as any)
const AppManagerScheduleRoute = AppManagerScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppManagerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager': typeof AppManagerRouteWithChildren
  '/manager/money': typeof AppManagerMoneyRoute
  '/manager/pantry': typeof AppManagerPantryRoute
  '/manager/pass': typeof AppManagerPassRoute
  '/manager/people': typeof AppManagerPeopleRoute
  '/manager/schedule': typeof AppManagerScheduleRoute
  '/manager/': typeof AppManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manager/money': typeof AppManagerMoneyRoute
  '/manager/pantry': typeof AppManagerPantryRoute
  '/manager/pass': typeof AppManagerPassRoute
  '/manager/people': typeof AppManagerPeopleRoute
  '/manager/schedule': typeof AppManagerScheduleRoute
  '/manager': typeof AppManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/manager': typeof AppManagerRouteWithChildren
  '/_app/manager/money': typeof AppManagerMoneyRoute
  '/_app/manager/pantry': typeof AppManagerPantryRoute
  '/_app/manager/pass': typeof AppManagerPassRoute
  '/_app/manager/people': typeof AppManagerPeopleRoute
  '/_app/manager/schedule': typeof AppManagerScheduleRoute
  '/_app/manager/': typeof AppManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manager'
    | '/manager/money'
    | '/manager/pantry'
    | '/manager/pass'
    | '/manager/people'
    | '/manager/schedule'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manager/money'
    | '/manager/pantry'
    | '/manager/pass'
    | '/manager/people'
    | '/manager/schedule'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/manager'
    | '/_app/manager/money'
    | '/_app/manager/pantry'
    | '/_app/manager/pass'
    | '/_app/manager/people'
    | '/_app/manager/schedule'
    | '/_app/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/manager': {
      id: '/_app/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AppManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manager/': {
      id: '/_app/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AppManagerIndexRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/money': {
      id: '/_app/manager/money'
      path: '/money'
      fullPath: '/manager/money'
      preLoaderRoute: typeof AppManagerMoneyRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/pantry': {
      id: '/_app/manager/pantry'
      path: '/pantry'
      fullPath: '/manager/pantry'
      preLoaderRoute: typeof AppManagerPantryRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/pass': {
      id: '/_app/manager/pass'
      path: '/pass'
      fullPath: '/manager/pass'
      preLoaderRoute: typeof AppManagerPassRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/people': {
      id: '/_app/manager/people'
      path: '/people'
      fullPath: '/manager/people'
      preLoaderRoute: typeof AppManagerPeopleRouteImport
      parentRoute: typeof AppManagerRoute
    }
    '/_app/manager/schedule': {
      id: '/_app/manager/schedule'
      path: '/schedule'
      fullPath: '/manager/schedule'
      preLoaderRoute: typeof AppManagerScheduleRouteImport
      parentRoute: typeof AppManagerRoute
    }
  }
}

interface AppManagerRouteChildren {
  AppManagerMoneyRoute: typeof AppManagerMoneyRoute
  AppManagerPantryRoute: typeof AppManagerPantryRoute
  AppManagerPassRoute: typeof AppManagerPassRoute
  AppManagerPeopleRoute: typeof AppManagerPeopleRoute
  AppManagerScheduleRoute: typeof AppManagerScheduleRoute
  AppManagerIndexRoute: typeof AppManagerIndexRoute
}

const AppManagerRouteChildren: AppManagerRouteChildren = {
  AppManagerMoneyRoute: AppManagerMoneyRoute,
  AppManagerPantryRoute: AppManagerPantryRoute,
  AppManagerPassRoute: AppManagerPassRoute,
  AppManagerPeopleRoute: AppManagerPeopleRoute,
  AppManagerScheduleRoute: AppManagerScheduleRoute,
  AppManagerIndexRoute: AppManagerIndexRoute,
}

const AppManagerRouteWithChildren = AppManagerRoute._addFileChildren(
  AppManagerRouteChildren,
)

interface AppRouteChildren {
  AppManagerRoute: typeof AppManagerRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppManagerRoute: AppManagerRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
